// ctf-enhanced/src/components/Navbar.tsx
import React from 'react';
import { Menu, Trophy, User2, LogOut, Shield, Award, Activity } from 'lucide-react';

interface NavbarProps {
  onPageChange: (page: 'challenges' | 'profile' | 'team' | 'teams' | 'admin' | 'scoreboard') => void;
}

export default function Navbar({ onPageChange }: NavbarProps) {
  return (
    <nav className="bg-indigo-600 text-white shadow-lg">
      <div className="max-w-7xl mx-auto px-4">
        <div className="flex items-center justify-between h-16">
          <div className="flex items-center space-x-4">
            <button className="lg:hidden p-2 rounded-md hover:bg-indigo-500">
              <Menu size={24} />
            </button>
            <div className="flex items-center space-x-2">
              <Trophy size={24} className="text-yellow-300" />
              <span className="font-bold text-xl">CTF Arena</span>
            </div>
          </div>
          
          <div className="hidden lg:flex items-center space-x-8">
            <button onClick={() => onPageChange('challenges')} className="hover:text-indigo-200">
              Challenges
            </button>
            <button onClick={() => onPageChange('teams')} className="hover:text-indigo-200">
              Teams
            </button>
            <button onClick={() => onPageChange('team')} className="hover:text-indigo-200">
              My Team
            </button>
            <button onClick={() => onPageChange('scoreboard')} className="hover:text-indigo-200 flex items-center space-x-1">
              <Award size={16} />
              <span>Scoreboard</span>
            </button>
            <button onClick={() => onPageChange('admin')} className="hover:text-indigo-200 flex items-center space-x-1">
              <Shield size={16} />
              <span>Admin</span>
            </button>
          </div>

          <div className="flex items-center space-x-4">
            <button className="p-2 rounded-full hover:bg-indigo-500">
              <Activity size={20} />
            </button>
            <button 
              onClick={() => onPageChange('profile')}
              className="p-2 rounded-full hover:bg-indigo-500"
            >
              <User2 size={20} />
            </button>
            <button className="p-2 rounded-full hover:bg-indigo-500">
              <LogOut size={20} />
            </button>
          </div>
        </div>
      </div>
    </nav>
  );
}

// Ctf-platform/src/components/Navbar.svelte
<script lang="ts">
    import { Link } from "svelte-routing";
    import { user } from '../stores/user';
  
    let showMobileMenu = false;
    let showUserMenu = false;
  
    $: isLoggedIn = !!$user;
  </script>
  
  <nav class="bg-gray-800 shadow-lg">
    <div class="container mx-auto px-4">
      <div class="flex justify-between items-center h-16">
        <div class="flex items-center">
          <Link to="/" class="text-xl font-bold">CTF Platform</Link>
        </div>
  
        <!-- Mobile menu button -->
        <button
          class="md:hidden p-2"
          on:click={() => showMobileMenu = !showMobileMenu}
        >
          <svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d={showMobileMenu ? "M6 18L18 6M6 6l12 12" : "M4 6h16M4 12h16M4 18h16"}
            />
          </svg>
        </button>
  
        <!-- Desktop menu -->
        <div class="hidden md:flex items-center space-x-4">
          <Link to="/" class="hover:text-blue-400">Challenges</Link>
          <Link to="/leaderboard" class="hover:text-blue-400">Leaderboard</Link>
          <Link to="/teams" class="hover:text-blue-400">Teams</Link>
          {#if isLoggedIn}
            <Link to="/achievements" class="hover:text-blue-400">Achievements</Link>
            <div class="relative">
              <button
                class="flex items-center gap-2 hover:text-blue-400"
                on:click={() => showUserMenu = !showUserMenu}
              >
                <span>{$user?.username}</span>
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M19 9l-7 7-7-7"
                  />
                </svg>
              </button>
              {#if showUserMenu}
                <div
                  class="absolute right-0 mt-2 w-48 bg-gray-700 rounded-lg shadow-lg py-2"
                  on:mouseleave={() => showUserMenu = false}
                >
                  <Link
                    to="/profile"
                    class="block px-4 py-2 hover:bg-gray-600"
                    on:click={() => showUserMenu = false}
                  >
                    Profile
                  </Link>
                  <Link
                    to="/settings"
                    class="block px-4 py-2 hover:bg-gray-600"
                    on:click={() => showUserMenu = false}
                  >
                    Settings
                  </Link>
                  <button
                    class="block w-full text-left px-4 py-2 text-red-400 hover:bg-gray-600"
                    on:click={() => {
                      user.logout();
                      showUserMenu = false;
                    }}
                  >
                    Logout
                  </button>
                </div>
              {/if}
            </div>
          {:else}
            <Link to="/login" class="hover:text-blue-400">Login</Link>
            <Link
              to="/signup"
              class="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded transition-colors duration-300"
            >
              Sign Up
            </Link>
          {/if}
        </div>
      </div>
  
      <!-- Mobile menu -->
      {#if showMobileMenu}
        <div class="md:hidden py-4 space-y-2">
          <Link
            to="/"
            class="block px-4 py-2 hover:bg-gray-700 rounded"
            on:click={() => showMobileMenu = false}
          >
            Challenges
          </Link>
          <Link
            to="/leaderboard"
            class="block px-4 py-2 hover:bg-gray-700 rounded"
            on:click={() => showMobileMenu = false}
          >
            Leaderboard
          </Link>
          <Link
            to="/teams"
            class="block px-4 py-2 hover:bg-gray-700 rounded"
            on:click={() => showMobileMenu = false}
          >
            Teams
          </Link>
          {#if isLoggedIn}
            <Link
              to="/achievements"
              class="block px-4 py-2 hover:bg-gray-700 rounded"
              on:click={() => showMobileMenu = false}
            >
              Achievements
            </Link>
            <Link
              to="/profile"
              class="block px-4 py-2 hover:bg-gray-700 rounded"
              on:click={() => showMobileMenu = false}
            >
              Profile
            </Link>
            <Link
              to="/settings"
              class="block px-4 py-2 hover:bg-gray-700 rounded"
              on:click={() => showMobileMenu = false}
            >
              Settings
            </Link>
            <button
              class="block w-full text-left px-4 py-2 text-red-400 hover:bg-gray-700 rounded"
              on:click={() => {
                user.logout();
                showMobileMenu = false;
              }}
            >
              Logout
            </button>
          {:else}
            <Link
              to="/login"
              class="block px-4 py-2 hover:bg-gray-700 rounded"
              on:click={() => showMobileMenu = false}
            >
              Login
            </Link>
            <Link
              to="/signup"
              class="block px-4 py-2 bg-blue-600 hover:bg-blue-700 rounded"
              on:click={() => showMobileMenu = false}
            >
              Sign Up
            </Link>
          {/if}
        </div>
      {/if}
    </div>
  </nav>
